name: daily tech podcast
on:   
  # Triggers the workflow on a schedule, every day at 00:00 UTC
  # schedule:    
  #   - cron: "0 0 * * *"  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  my-job:
    name: Run MATLAB Script
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
      - name: Run script
        uses: matlab-actions/run-command@v2
        with:
          command: dailytechtask
      - name: Archive output data
        uses: actions/upload-artifact@v4
        with:
          name: podcast
          path: podcast/tech_[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]/
# env:
#   OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
#   ELEVEN_API_KEY: ${{secrets.ELEVEN_API_KEY}}
